project/models/basket.py
from project import db


class BasketItem(db.Model):
    __tablename__ = 'basket_item'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), index=True,
                        nullable=False)
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'),
                           nullable=False)
    product = db.relationship('Product')
    quantity = db.Column(db.Numeric(precision=15, scale=3), nullable=False)

project/models/product.py
from project import db
from project.models.product_type import ProductType


class Product(db.Model):
    __tablename__ = 'product'
    ENTITY_NAME = 'Товар'
    ENTITY_NAME_PLURAL = 'Товары'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), index=True)
    product_type_id = db.Column(db.Integer, db.ForeignKey('product_type.id'),
                                nullable=False)
    product_type = db.relationship(ProductType)
    description = db.Column(db.Text)
    primary_image_id = db.Column(db.Integer, db.ForeignKey('product_image.id'))

    def __repr__(self):
        return f'"{self.name}" [код {self.id}]'

project/forms/product.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField
from wtforms_sqlalchemy.orm import QuerySelectField
from wtforms.validators import DataRequired

from project.models.product_type import ProductType


class ProductForm(FlaskForm):
    name = StringField('Наименование', validators=[DataRequired()],
                       render_kw={'class': 'form-control'})
    product_type = QuerySelectField(
        'Тип товара', validators=[DataRequired()],
        query_factory=lambda: ProductType.query,
        get_label='name', render_kw={'class': 'form-control'}
    )
    description = TextAreaField(
        'Описание', validators=[],
        render_kw={'class': 'form-control', "rows": 11}
    )
    quantity = IntegerField(
        'Количество', validators=[],
        render_kw={'class': 'form-control',
                   'type': 'number', 'min': '1',
                   'value': '1',
                   'size': '3'}
    )
    submit = SubmitField('Сохранить', render_kw={'class': 'btn btn-info'})

project/forms/product_type.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms_sqlalchemy.orm import QuerySelectField
from wtforms.validators import DataRequired

from project.models.product_type import ProductType


class ProductTypeForm(FlaskForm):
    name = StringField('Наименование', validators=[DataRequired()],
                       render_kw={'class': 'form-control'})
    parent = QuerySelectField(
        'Родитель',
        validators=[],
        query_factory=lambda: ProductType.query,
        get_label='name',
        allow_blank=True,
        blank_text=f'Выберите {ProductType.ENTITY_NAME.lower()}...',
        render_kw={'class': 'form-control'})
    submit = SubmitField('Сохранить', render_kw={'class': 'btn btn-info'})

project/routes/basket.py
from datetime import datetime

from flask import Blueprint, render_template, abort, redirect, url_for, flash
from flask_login import login_required, current_user

from project import db
from project.models.basket import BasketItem
from project.models.order import Order, OrderItem

basket_blueprint = Blueprint('basket', __name__, url_prefix='/basket',
                             template_folder='templates')


@basket_blueprint.route('/')
@login_required
def item_list():
    items = BasketItem.query.filter_by(user_id=current_user.id).order_by(
        'id').all()
    return render_template('basket.html', title='Корзина', item_list=items)


@basket_blueprint.route('/remove/<int:item_id>', methods=['POST'])
@login_required
def item_remove(item_id):
    item = BasketItem.query.filter_by(id=item_id).first_or_404()
    if item.user_id != current_user.id:
        abort(403)
    db.session.delete(item)
    db.session.commit()
    return redirect(url_for('basket.item_list'))


@basket_blueprint.route('/checkout', methods=['POST'])
@login_required
def checkout():
    basket_items = BasketItem.query.filter_by(user_id=current_user.id).all()
    if len(basket_items) == 0:
        return redirect(url_for('basket.item_list'))
    try:
        order = Order()
        order.date_order_placed = datetime.now()
        order.user_id = current_user.id
        order.customer_id = current_user.customer_id
        db.session.add(order)
        db.session.commit()
        for basket_item in basket_items:
            order_item = OrderItem()
            order_item.order_id = order.id
            order_item.product_id = basket_item.product_id
            order_item.quantity = basket_item.quantity
            order_item.price = 0
            order_item.amount = 0
            db.session.add(order_item)
            db.session.delete(basket_item)
        db.session.commit()
        flash('Заказ успешно оформлен', 'success')
        return redirect(url_for('products.product_list'))
    except Exception as exc:
        flash(str(exc), 'error')
        flash('Ошибка создания заказа', 'error')
        return redirect(url_for('basket.item_list'))

project/routes/image.py
import os

from flask import Blueprint, send_from_directory, request, abort, \
    render_template, flash, redirect, url_for
from flask_login import login_required
from sqlalchemy import and_
from werkzeug.utils import secure_filename

from config import Config
from project import db
from project.models.image import ProductImage
from project.models.product import Product

images_blueprint = Blueprint('images', __name__, url_prefix='/images',
                             template_folder='templates')


@images_blueprint.route('/<int:image_id>')
def image(image_id):
    img = ProductImage.query.filter_by(id=image_id).first_or_404()
    return send_from_directory(Config.IMAGES_FOLDER, img.filename)


@images_blueprint.route('/product/<int:product_id>', methods=['GET'])
@login_required
def product_images(product_id):
    product = Product.query.filter_by(id=product_id).first_or_404()
    image_list = ProductImage.query.filter_by(product_id=product_id)
    return render_template('product_image_list.html', product=product,
                           images=image_list,
                           title=f'{product} (Изображения)')


@images_blueprint.route('/product/<int:product_id>/new',
                        methods=['GET', 'POST'])
@login_required
def image_new(product_id):
    def allowed_file(filename):
        return '.' in filename and \
               filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_EXTENSIONS

    product = Product.query.filter_by(id=product_id).first_or_404()
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part', 'error')
            return redirect(request.url)
        file = request.files['file']
        if file.filename == '':
            flash('No selected file', 'error')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            img_name = f'{product_id}-{hash(file)}' \
                       f'-{secure_filename(file.filename)}'
            file.save(os.path.join(Config.IMAGES_FOLDER, img_name))
            p_image = ProductImage()
            p_image.product_id = product_id
            p_image.filename = img_name
            db.session.add(p_image)
            db.session.commit()
            if product.primary_image_id is None:
                product.primary_image_id = p_image.id
                db.session.add(product)
                db.session.commit()
            return redirect(
                url_for('images.product_images', product_id=product_id))
    return render_template('image_new.html', product=product,
                           title=f'Добавить файл для {product}')


@images_blueprint.route('/product/<int:product_id>/primary/resized/<int:size>',
                        methods=['GET'])
@login_required
def primary_image_resized(product_id, size):
    product = Product.query.filter_by(id=product_id).first_or_404()
    return resize_image(product.primary_image_id, size)


@images_blueprint.route(
    '/product/<int:product_id>/<int:image_id>/resized/<int:size>',
    methods=['GET'])
@login_required
def image_resized(product_id, image_id, size):
    img = ProductImage.query.filter(
        and_(ProductImage.id == image_id,
             ProductImage.product_id == product_id)).first_or_404()
    return resize_image(img.id, size)


def resize_image(image_id, size):
    allowed_sizes = [100, 250]
    if size not in allowed_sizes:
        abort(403)
    img = ProductImage.query.filter_by(id=image_id).first_or_404()
    original_path = os.path.join(Config.IMAGES_FOLDER, img.filename)
    dir_path = os.path.join(Config.IMAGES_FOLDER, str(size))
    if os.path.exists(os.path.join(dir_path, img.filename)):
        return send_from_directory(dir_path, img.filename)
    else:
        if not os.path.exists(dir_path):
            os.makedirs(dir_path)
        from PIL import Image
        with Image.open(original_path) as src_img:
            result_img = src_img.resize((size, size))
        result_img.save(os.path.join(dir_path, img.filename))
        return send_from_directory(dir_path, img.filename)

project/routes/product.py
from flask_login import login_required, current_user
from flask import render_template, Blueprint, flash, redirect, url_for

from project import db
from project.forms.product import ProductForm
from project.models.basket import BasketItem
from project.models.product import Product
from project.models.image import ProductImage

products_blueprint = Blueprint('products', __name__, url_prefix='/products',
                               template_folder='templates')


@products_blueprint.route('/')
@login_required
def product_list():
    item_list = Product.query.order_by('name').all()
    return render_template('product_list.html',
                           title=f'{Product.ENTITY_NAME_PLURAL}',
                           item_list=item_list)


@products_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
def product_new():
    product = Product()
    form = ProductForm(obj=product)
    if form.validate_on_submit():
        form.populate_obj(product)
        db.session.add(product)
        db.session.commit()
        flash('Элемент успешно создан', 'success')
        return redirect(url_for('products.product_list'))
    return render_template('product_edit.html',
                           product=product, is_new=True, form=form,
                           title=f'{product.ENTITY_NAME} (Новый)')


@products_blueprint.route('/<int:product_id>/edit', methods=['GET', 'POST'])
@login_required
def product_edit(product_id):
    product = Product.query.filter_by(id=product_id).first_or_404()
    form = ProductForm(obj=product)
    if form.validate_on_submit():
        form.populate_obj(product)
        db.session.add(product)
        db.session.commit()
        flash('Изменения были сохранены', 'success')
        return redirect(url_for('products.product_list'))
    return render_template('product_edit.html', product=product, form=form,
                           title=f'{product}')


@products_blueprint.route('/<int:product_id>', methods=['GET', 'POST'])
@login_required
def product_view(product_id):
    product = Product.query.filter_by(id=product_id).first_or_404()
    form = ProductForm(obj=product)
    image_list = ProductImage.query.filter_by(product_id=product_id)
    primary_image = ProductImage.query.get(product.primary_image_id)
    if form.validate_on_submit():
        # add to basket
        basket_item = BasketItem()
        basket_item.user_id = current_user.id
        basket_item.product_id = product.id
        basket_item.quantity = form.quantity.data
        db.session.add(basket_item)
        db.session.commit()
        flash('Товар добавлен в корзину', 'info')
    return render_template('product_view.html', title=product, form=form,
                           images=image_list,
                           primary_image=primary_image, product_id=product_id)

project/routes/product_type.py
from flask_login import login_required
from flask import render_template, Blueprint, flash, redirect, url_for
from sqlalchemy import text

from project import db
from project.forms.product_type import ProductTypeForm
from project.models.product_type import ProductType

product_types_blueprint = Blueprint('product_types', __name__,
                                    url_prefix='/product_types',
                                    template_folder='templates')


@product_types_blueprint.route('/')
@login_required
def product_type_list():
    sql_text = text(
        'select '
        '   p.id, p.name, coalesce(pp.name, "") as parent_name '
        'from product_type as p '
        '   left join product_type as pp '
        '   on p.parent_id=pp.id '
        'order by p.name')
    item_list = db.session.query('id', 'name', 'parent_name').from_statement(
        sql_text).all()
    return render_template('product_type_list.html',
                           title=ProductType.ENTITY_NAME_PLURAL,
                           item_list=item_list)


@product_types_blueprint.route('/edit/<entity_id>', methods=['GET', 'POST'])
@login_required
def product_type_edit(entity_id):
    obj = ProductType.query.filter_by(id=entity_id).first_or_404()
    parent = ProductType.query.filter_by(id=obj.parent_id).first()
    form = ProductTypeForm(id=obj.id, name=obj.name, parent=parent)
    if form.validate_on_submit():
        obj.name = form.name.data
        if form.parent.data is not None:
            obj.parent_id = form.parent.data.id
        db.session.add(obj)
        db.session.commit()
        flash('Изменения были сохранены', 'success')
        return redirect(url_for('product_types.product_type_list'))
    return render_template('product_type_edit.html', title=obj, form=form)


@product_types_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
def product_type_new():
    obj = ProductType()
    form = ProductTypeForm(obj=obj)
    if form.validate_on_submit():
        obj.name = form.name.data
        if form.parent.data is not None:
            obj.parent_id = form.parent.data.id
        db.session.add(obj)
        db.session.commit()
        flash(f'{ProductType.ENTITY_NAME} успешно создан', 'success')
        return redirect(url_for('product_types.product_type_list'))
    return render_template('product_type_edit.html',
                           title=f'{ProductType.ENTITY_NAME} (Новый)',
                           form=form)

project/routes/user.py
from flask import render_template, flash, redirect, url_for, request, Blueprint
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from datetime import datetime, timedelta

from project.forms.user import RegistrationForm, LoginForm, EditProfileForm
from project import db
from project.models.user import User

users_blueprint = Blueprint('users', __name__, url_prefix='/orders',
                            template_folder='templates')


@users_blueprint.before_request
def before_request():
    if current_user.is_authenticated:
        now = datetime.utcnow()
        if current_user.last_seen is None or (
                now - current_user.last_seen > timedelta(
                minutes=1)):  # to reduce writing to database
            db.session.add(current_user)
        current_user.last_seen = now
        db.session.commit()


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        usr = User.query.filter_by(username=form.username.data).first()
        if usr is None or not usr.check_password(form.password.data):
            flash('Неверные имя пользователя или пароль', 'error')
            return redirect(url_for('users.login'))
        login_user(usr, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('index')
        return redirect(next_page)
    return render_template('login.html', title='Вход', form=form)


@users_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        usr = User(username=form.username.data, email=form.email.data)
        usr.set_password(form.password.data)
        db.session.add(usr)
        db.session.commit()
        flash('Позравляем с регистрацией! Теперь вы можете войти', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Регистрация', form=form)


@users_blueprint.route('/<username>')
@login_required
def user(username):
    usr = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=usr, title=f'{usr}')


@users_blueprint.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Изменения были сохранены', 'success')
        return redirect(url_for('users.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title='Изменить профиль',
                           form=form)

project/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="shortcut icon" type="image/icon" href="{{ url_for('static', filename='favicon.ico') }}"/>
    <title>
        {{ title }}
    </title>
</head>
<body>
<div class="container">
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('index') }}">Магазин</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('products.product_list') }}">Каталог</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('index') }}">О магазине</a>
                    </li>
                    {% if current_user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Войти</a>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ current_user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('orders.order_list') }}">Заказы</a>
                                <a class="dropdown-item" href="{{ url_for('users.edit_profile') }}">Профиль</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ url_for('product_types.product_type_list') }}">Типы товаров</a>
                                <a class="dropdown-item" href="{{ url_for('products.product_list') }}">Товары</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ url_for('users.logout') }}">Выйти</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
                <form class="form-inline my-2 my-lg-0 mr-5">
                    <input class="form-control mr-sm-2" type="search" placeholder="Найти товары" aria-label="Поиск">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Поиск</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="nav-item" href="{{ url_for('basket.item_list') }}">
                            <button class="btn my-2 my-lg-0 {% if request.path != url_for('basket.item_list') %} btn-warning {% endif %}">
                                Корзина
                            </button>
                        </a>

                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div>
        <br>
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for (category, message) in messages %}
                    {% if category=='info' %}
                        <div class="alert alert-info">{{ message }}</div>
                    {% elif category=='success' %}
                        <div class="alert alert-success">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-danger" role="alert">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% block content %}
    {% endblock %}
</div>

<script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% block script %}
{% endblock %}
</body>
</html>

project/templates/basket.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}</h1>
    <table class="table table-bordered table-condensed table-hover">
        <thead>
        <tr class="table-row thead-light">
            <th></th>
            <th></th>
            <th>Товар</th>
            <th>Количество</th>
        </tr>
        </thead>
        <tbody>
        {% for item in item_list %}
            <tr class="table-row">
                <td width="10" class="align-middle">
                    <form method="post" action="{{ url_for('basket.item_remove', item_id=item.id) }}">
                        <button type="submit" class="btn btn-sm btn-outline-secondary">
                            &#10005
                        </button>
                    </form>
                </td>
                <td width="100" class="align-middle">
                    <img src="{{ url_for('images.primary_image_resized', product_id=item.product_id, size=100) }}">
                </td>
                <td class="clickable-cell align-middle"
                    data-href="{{ url_for('products.product_view', product_id=item.product_id) }}">
                    {{ item.product }}
                </td>
                <td width="20" class="align-middle">
                    {{ item.quantity }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <form method="post" action="{{ url_for('basket.checkout') }}">
        <button class="btn btn-lg btn-warning m-2">Оформить заказ</button>
    </form>
{% endblock %}

{% block script %}
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-cell").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

project/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Вход</h1>
    <form action='' method='post' novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>Еще не зарегистрированы? <a href="{{ url_for('users.register') }}">Зарегистрируйтесь!</a></p>
{% endblock %}

project/templates/product_edit.html
{% extends "base.html" %}

{% block content %}
    <h1>
        {% if is_new %}
            {{ title }}
        {% else %}
            <div>
                {{ title }}
                <a class="float-right" href="{{ url_for('images.product_images', product_id=product.id) }}">Изображения</a>
            </div>
        {% endif %}
    </h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}

        {% for field in form if not field.widget.input_type in ('hidden', 'submit') and not field.name in ('quantity') %}
            <div class="form-group">
                {{ field.label() }}
                {{ field() }}
                {% for error in field.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
        {% endfor %}
        {{ form.submit() }}
        <a class="btn btn-secondary ml-3"
            {% if is_new %}
                href="{{ url_for('products.product_list') }}"
            {% else %}
                href="{{ url_for('products.product_view', product_id=product.id) }}"
            {% endif %}
            >Отмена
        </a>
    </form>
{% endblock %}

project/templates/product_image_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        <div>
            <a href="{{ url_for('products.product_edit', product_id=product.id) }}">{{ product }}</a>
            <p class="float-right">Изображения</p>
        </div>
    </h1>
    <a class="btn btn-primary mt-3 mb-3" href="{{ url_for('images.image_new', product_id=product.id) }}">Добавить
        новое изображение</a>
    <div class="row">
        {% for image in images %}
            <div class="col-3">
                <a href="{{ url_for('images.image', image_id=image.id) }}">
                    <img class="img-fluid img-thumbnail"
                         src="{{ url_for('images.image_resized', product_id=image.product_id, image_id=image.id, size=250) }}"
                         alt="">
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

project/templates/product_list.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}</h1>
    <a class="btn btn-info mb-4 mt-3" href="{{ url_for('products.product_new') }}">Создать</a>
    <table class="table table-bordered table-condensed table-hover">
        <thead>
        <tr class="table-row thead-light">
            <th></th>
            <th>Наименование</th>
        </tr>
        </thead>
        <tbody>
        {% for item in item_list %}
            <tr class="table-row clickable-row"
                data-href="{{ url_for('products.product_view', product_id=item.id) }}">
                <td width="100">
                    <img src="{{ url_for('images.primary_image_resized', product_id=item.id, size=100) }}">
                </td>
                <td>
                    {{ item.name }}
                    <br>
                    {{ item.description }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block script %}
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

project/templates/product_type_list.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}</h1>
    <a class="btn btn-info mb-4 mt-3" href="{{ url_for('product_types.product_type_new') }}">Создать</a>
    <table class="table table-bordered table-condensed table-hover">
        <thead>
        <tr class="table-row thead-light">
            <th>Код</th>
            <th>Наименование</th>
            <th>Родитель</th>
        </tr>
        </thead>
        <tbody>
        {% for item in item_list %}
            <tr class="table-row clickable-row"
                data-href="{{ url_for('product_types.product_type_edit', entity_id=item.id) }}">
                <td>{{ item.id }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.parent_name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block script %}
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

project/templates/product_view.html
{% extends "base.html" %}

{% block content %}
    <h1>
        {{ title }}
        <a href="{{ url_for('products.product_edit', product_id=product_id) }}"
           style="text-decoration:none">&#10000;</a>
    </h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col-6 align-self-center">
                {% if primary_image %}
                    <a href="{{ url_for('images.image', image_id=primary_image.id) }}">
                        <img class="img-fluid" src="{{ url_for('images.image', image_id=primary_image.id) }}"
                             alt="">
                    </a>
                {% endif %}
                <div class="row mt-5">
                    {% for image in images %}
                        <div class="col-3 align-self-center">
                            <a href="{{ url_for('images.image', image_id=image.id) }}">
                                <img class="img-fluid img-thumbnail mb-2"
                                     src="{{ url_for('images.image_resized', product_id=image.product_id, image_id=image.id, size=100) }}"
                                     alt="">
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    {{ form.name.label }}
                    {{ form.name(readonly=True) }}
                </div>
                <div class="form-group">
                    {{ form.product_type.label }}
                    {{ form.product_type(readonly=True) }}
                </div>
                <div class="form-group">
                    {{ form.description.label }}
                    {{ form.description(readonly=True) }}
                </div>
                <div class="row">
                    {{ form.quantity(class='mr-3 ml-3') }}
                    {{ form.submit(value='Добавить в корзину') }}
                </div>
            </div>
        </div>
    </form>
{% endblock %}